### ISSUE TITLE
Add APP-6(D) to description of Military Symbol Editor button on MT ribbon

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-desktop-addins#100]
![image](https://user-images.githubusercontent.com/3800729/52453194-12147800-2afb-11e9-9f04-114075909f96.png)

MT 3.3 January 2019 release
Pro 2.3

**Comment by csmoore** [comment]
In PR #113, commit: https://github.com/Esri/military-tools-desktop-addins/pull/113/commits/36c3c28db279aa92f43fc9495f61863803b5338f

This text was changed to slightly more generic : "MIL-STD-2525 and APP-6" since 2525B/C/D and APP-6D/B are now supported:

![image](https://user-images.githubusercontent.com/3090809/59396183-83885f80-8d55-11e9-856b-5184f41bb851.png)

**Comment by lfunkhouser** [comment]
verified as fixed.
